import { Html, Head, Main, NextScript } from 'next/document'
import NavBar from '@/components/navbar'


export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>zshuck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <NavBar/>
        <Main/>
        <NextScript />
      </body>
    </Html>
  )
}
